"""The Insights information architecture, pinned.

The IA was chosen for what Driftwood publishes in three to five years, not for what the repo happens
to contain today. That makes it exactly the kind of decision that erodes silently: a page gets added,
someone drops it in the nearest menu, and within a year the masthead is a directory of the file
system again. Each rule below is a decision, with the reason attached.

The failure this repo has actually shipped twice is worth naming: (1) seven pages sat in the nav but
were never registered in sync_docs.py, so they 404'd in production from ~43 linking pages; (2) the
"Articles" entry pointed at insights.html, which was a redirect stub back to research.html — a
sibling entry in the same menu. Menu entries that don't resolve, or that round-trip the reader, are
the thing these tests exist to prevent.
"""
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "src" / "drift" / "web"
DOCS = ROOT / "docs"
INSIGHTS = WEB / "insights.html"

# The primary masthead. Five families and two actions — the whole navigation.
FAMILIES = ("Our Firm", "Coordination", "Insights", "Professionals")

# Inside Insights, in this order. This tuple IS the specification.
#
# Decision Memos was reserved on 2026-07-31 and deliberately withheld from the masthead until a memo
# existed, because a menu entry with nothing behind it is the defect this repo has already shipped
# twice. It joined on 2026-08-01 with two entries — the new domicile-sequencing memo and ic-memo.html,
# which the overlap check found was already a decision memo filed under an investment-only name.
INSIGHTS_CHILDREN = (
    ("Research", "research.html"),
    ("Commentary", "commentary.html"),
    ("The Driftwood Review", "driftwood-review.html"),
    ("Decision Memos", "insights.html#decision-memos"),
    ("Decision Tools", "insights.html#decision-tools"),
    ("Decision Library", "insights.html#decision-library"),
)

DECISION_TOOLS = ("statemap.html", "leakage.html", "taxlab.html", "concentration.html")
DECISION_LIBRARY = ("case-business-sale.html", "case-inheritance.html", "case-stock-options.html",
                    "case-moving-states.html", "case-rmds.html", "case-widowed.html",
                    "case-vacation-home.html", "case-charitable-giving.html")


def _nav_pages():
    """Every source page carrying the shared Phase-2 masthead."""
    return sorted(p for p in WEB.glob("*.html")
                  if 'class="dwnav dwnav--phase2"' in p.read_text(encoding="utf-8"))


def _is_noindex(text: str) -> bool:
    """Read the actual robots meta tag, not the word. Prose about a page's history — including the
    comments explaining why insights.html stopped being a noindex stub — must not trip this."""
    m = re.search(r'<meta[^>]+name="robots"[^>]*>', text)
    return bool(m) and "noindex" in m.group(0)


def _panel(text: str, family: str) -> str:
    """The dropdown panel markup for one family on one page."""
    m = re.search(
        r'>%s<span class="caret"[^>]*></span></button><div class="dwnav-panel">(.*?)</div>'
        % re.escape(family), text, re.S)
    return m.group(1) if m else ""


# ── the masthead is the same everywhere ───────────────────────────────────────────────────────

def test_every_page_carries_the_same_four_families():
    """A masthead that differs page to page is the symptom of hand-edited nav. It is generated by
    scripts/phase2_nav.py precisely so it cannot drift."""
    pages = _nav_pages()
    assert len(pages) >= 45, f"only {len(pages)} pages carry the masthead"
    for p in pages:
        t = p.read_text(encoding="utf-8")
        for fam in FAMILIES:
            assert f'>{fam}<span class="caret"' in t, f"{p.name} is missing the {fam!r} family"


def test_the_research_family_was_renamed_to_insights_everywhere():
    """'Insights & Research' named a subset. 'Research' is one division inside Insights; it cannot
    also name the set that contains it."""
    for p in _nav_pages():
        t = p.read_text(encoding="utf-8")
        nav = re.search(r"<nav class=\"dwnav dwnav--phase2\".*?</nav>", t, re.S)
        assert nav, f"{p.name}: no masthead"
        assert "Insights &amp; Research" not in nav.group(0), f"{p.name} still says Insights & Research"


def test_articles_is_gone_from_the_navigation():
    """It named a FORMAT, not a subject — and it pointed at insights.html, which redirected back to
    research.html, another entry in the same menu. The URL still exists; the menu entry does not."""
    for p in _nav_pages():
        nav = re.search(r"<nav class=\"dwnav dwnav--phase2\".*?</nav>",
                        p.read_text(encoding="utf-8"), re.S).group(0)
        assert ">Articles<" not in nav, f"{p.name} still lists Articles in the nav"


def test_insights_holds_exactly_the_agreed_divisions_in_order():
    for p in _nav_pages():
        panel = _panel(p.read_text(encoding="utf-8"), "Insights")
        assert panel, f"{p.name}: no Insights panel"
        found = re.findall(r'<a href="([^"]+)"[^>]*>([^<]+)</a>', panel)
        assert [(lbl, href) for href, lbl in found] == list(INSIGHTS_CHILDREN), \
            f"{p.name}: Insights panel is {found}"


def test_the_masthead_carries_no_more_than_the_agreed_families():
    """Guards against a sixth family quietly appearing. Adding one is a deliberate edit to FAMILIES
    above, not a change to fifty pages."""
    for p in _nav_pages():
        nav = re.search(r"<nav class=\"dwnav dwnav--phase2\".*?</nav>",
                        p.read_text(encoding="utf-8"), re.S).group(0)
        n = nav.count('class="dwnav-trigger"')
        assert n == len(FAMILIES), f"{p.name} has {n} families, expected {len(FAMILIES)}"


# ── every menu entry resolves ─────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("label,href", INSIGHTS_CHILDREN)
def test_every_insights_entry_resolves_to_a_built_page(label, href):
    """The bug this repo shipped: nav entries whose pages were never registered in sync_docs.py."""
    page, _, anchor = href.partition("#")
    built = DOCS / page
    assert built.exists(), f"{label} -> {page} is not built (register it in scripts/sync_docs.py)"
    if anchor:
        assert f'id="{anchor}"' in built.read_text(encoding="utf-8"), \
            f"{label} -> #{anchor} does not exist on {page}"


def test_no_menu_entry_round_trips_the_reader_to_a_sibling():
    """An entry that redirects to another entry in the same menu wastes a slot and confuses the
    reader — exactly what Articles -> insights.html -> research.html used to do."""
    for label, href in INSIGHTS_CHILDREN:
        page = href.partition("#")[0]
        t = (DOCS / page).read_text(encoding="utf-8")
        assert 'http-equiv="refresh"' not in t, f"{label} -> {page} is a redirect stub"
        assert not _is_noindex(t), f"{label} -> {page} is noindex but sits in the primary nav"


# ── the Insights landing page ─────────────────────────────────────────────────────────────────

def test_insights_is_a_real_indexable_landing_page():
    """It was a noindex redirect stub. It is now the page the nav family names."""
    t = INSIGHTS.read_text(encoding="utf-8")
    assert 'http-equiv="refresh"' not in t
    assert not _is_noindex(t)
    assert 'href="https://driftwoodwealth.com/insights.html"' in t, "canonical must be self-referential"
    assert "<h1>Insights</h1>" in t


def test_the_landing_page_carries_every_division_in_order():
    """The landing page's sections and the masthead's entries are one specification, so they are
    checked against the same tuple rather than against two hand-kept lists."""
    t = INSIGHTS.read_text(encoding="utf-8")
    anchors = re.findall(r'<section class="sec" id="([a-z-]+)"', t)
    expected = [href.partition("#")[2] or href.replace(".html", "").replace("-", "-")
                for _, href in INSIGHTS_CHILDREN]
    expected = ["research", "commentary", "the-driftwood-review",
                "decision-memos", "decision-tools", "decision-library"]
    assert anchors == expected, anchors
    # and the numerals must run in sequence, so a new division cannot land mid-page unnumbered
    numerals = re.findall(r'<span class="sec-num">([IVX]+)</span>', t)
    assert numerals == ["I", "II", "III", "IV", "V", "VI"], numerals


def test_decision_tools_section_lists_every_shipped_tool():
    """The tools exist and are public; the shelf must show all of them, or the shelf is a teaser."""
    section = re.search(r'id="decision-tools".*?</section>', INSIGHTS.read_text(encoding="utf-8"), re.S)
    assert section
    for tool in DECISION_TOOLS:
        assert f'href="{tool}"' in section.group(0), f"Decision Tools omits {tool}"


def test_decision_library_lists_every_worked_decision():
    """Every case-*.html in the repo is a worked decision and belongs on the shelf. A case study
    that exists but is unreachable from the library is an orphan."""
    section = re.search(r'id="decision-library".*?</section>', INSIGHTS.read_text(encoding="utf-8"), re.S)
    assert section
    on_disk = {p.name for p in WEB.glob("case-*.html")}
    assert on_disk == set(DECISION_LIBRARY), (
        f"the library roster drifted from disk: on disk but not listed "
        f"{sorted(on_disk - set(DECISION_LIBRARY))}, listed but absent "
        f"{sorted(set(DECISION_LIBRARY) - on_disk)}"
    )
    for case in DECISION_LIBRARY:
        assert f'href="{case}"' in section.group(0), f"Decision Library omits {case}"


def test_the_tools_advertised_are_only_the_ones_that_exist():
    """No roadmap on the shelf. Listing an unbuilt Business Exit Review would be advertising vapor;
    the roadmap lives in OPERATIONS.md until a tool ships."""
    section = re.search(r'id="decision-tools".*?</section>',
                        INSIGHTS.read_text(encoding="utf-8"), re.S).group(0)
    hrefs = {h.partition("#")[0] for h in re.findall(r'href="([^"]+)"', section)}
    missing = sorted(h for h in hrefs if h.endswith(".html") and not (DOCS / h).exists())
    assert not missing, f"Decision Tools advertises unbuilt pages: {missing}"


def test_every_link_on_the_landing_page_resolves():
    t = INSIGHTS.read_text(encoding="utf-8")
    hrefs = {h.partition("#")[0] for h in re.findall(r'href="([^"]+)"', t)}
    broken = sorted(h for h in hrefs
                    if h.endswith(".html") and "://" not in h and not (DOCS / h).exists())
    assert not broken, f"broken links on the Insights landing page: {broken}"


# ── the old "Coordination Library" shelf ──────────────────────────────────────────────────────

def test_the_library_is_named_decision_library_everywhere():
    """It was the 'Coordination Library' and its label linked to research.html — a page with no
    library section on it, so the shelf named a place that did not exist."""
    for p in WEB.glob("*.html"):
        t = p.read_text(encoding="utf-8")
        assert "Coordination Library" not in t, f"{p.name} still says Coordination Library"


def test_every_case_study_points_back_at_the_library_shelf():
    for name in DECISION_LIBRARY:
        t = (WEB / name).read_text(encoding="utf-8")
        assert 'href="insights.html#decision-library"' in t, \
            f"{name} does not link back to the Decision Library"
